modell: SFA Cobb-Douglas produktionsfront
ineffDecrease: yes
distribution: truncnorm
skattning: MLE
output: CU
input:
- OPEXp
- CAPEX
- MWhl
- MWhh
- MW
- NS
effektivitet: theta_final = exp(-û)
obs: 136
datum: '2025-08-05'
