modell: SFA Cobb-Douglas kostnadsfront
ineffDecrease: no
distribution: halvnormal
skattning: MLE
output: TOTEX
input:
- CU
- MWhl
- MWhh
- MW
- NS
effektivitet: theta_final = exp(-û)
obs: 136
datum: '2025-08-05'
