modell: DEA
parametrar:
  input_cols:
  - TOTEX
  multiplier: 2.0
  outlier_filter: true
  output_cols:
  - CU
  - MW
  - NS
  - MWhl
  - MWhh
  q_lower: 25
  q_upper: 75
  rts: crs
timestamp: 2025-11-10_07-53-42
