"""
config/data_paths.py

Single source of truth for where data files live.

Every data file in the project is registered here under a logical name. Loaders,
tests and scripts resolve paths through :func:`dataset_path` / :func:`require_dataset`
instead of hard-coding strings, so a directory reorganisation only changes the
``_REGISTRY`` table below.

The data root is the repository ``data/`` folder, overridable with the
environment variable ``REGUMETRICA_DATA_DIR`` (useful for deployments where the
data lives outside the source tree).
"""
from __future__ import annotations

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def data_dir() -> Path:
    """Return the data root (env override ``REGUMETRICA_DATA_DIR`` or ``<repo>/data``)."""
    env = os.environ.get("REGUMETRICA_DATA_DIR")
    return Path(env).expanduser() if env else PROJECT_ROOT / "data"


# Logical dataset name -> path relative to data_dir().
# Grouped by provenance; the relative paths are the only thing a future
# reorganisation needs to touch.
_REGISTRY: dict[str, str] = {
    # --- raw external sources (Ei deliverables, regulatory inputs) ---------
    "data_modeller": "raw/ei/Data_modeller.xlsx",
    "eis_dea": "raw/ei/EIs_DEA.xlsx",
    "sdf_running_costs": "raw/ei/Löpande kostnader från SDF 2024-27.xlsx",
    "adjustment_vars": "raw/adjustments/all_adjust_vars.csv",
    "network_areas_shapefile": "raw/shapefiles/all_network_operator_areas.shp",

    # --- derived (generated by scripts/ — KENT outputs + grunddata) --------
    "capbase_a": "derived/rab_and_capex/capbase_a.parquet",
    "capcost_a": "derived/rab_and_capex/capcost_a.parquet",
    "controllable_a": "derived/opex/controllable_a.parquet",
    "controllable_meta": "derived/opex/controllable_meta.parquet",
    "non_controllable_a": "derived/opex/non_controllable_a.parquet",

    # --- frozen snapshots of raw Excel sources (built by ---------------
    #     scripts/freeze_raw_sources.py; loaded at runtime instead of the
    #     slow .xlsx files). Each is the exact transformed loader output.
    #     The SDF sheets are intentionally NOT frozen: they contain
    #     heterogeneous (mixed-type) Excel columns that do not round-trip
    #     through parquet safely, so they stay on .xlsx.
    "snap_data_modeller": "derived/snapshots/data_modeller.parquet",
    "snap_eis_dea": "derived/snapshots/eis_dea.parquet",

    # --- curated reference lookups ----------------------------------------
    "company_names": "reference/company_names.csv",
    "reconciliation": "reference/reconciliation_id_network_firm_dmu.csv",
    "avg_norm_value": "reference/avg_norm_value_by_category.parquet",

    # --- test fixtures (mini datasets, 3 companies) -----------------------
    "capbase_a_mini": "fixtures/capbase_a_mini.parquet",
    "controllable_a_mini": "fixtures/controllable_a_mini.parquet",
    "controllable_meta_mini": "fixtures/controllable_meta_mini.parquet",
    "non_controllable_a_mini": "fixtures/non_controllable_a_mini.parquet",
}


def dataset_path(name: str, base: str | Path | None = None) -> Path:
    """Resolve a registered dataset name to an absolute path (may not exist).

    Args:
        name: Logical dataset name (key in ``_REGISTRY``).
        base: Optional data-root override (defaults to :func:`data_dir`).
    """
    try:
        rel = _REGISTRY[name]
    except KeyError:
        raise KeyError(
            f"Unknown dataset {name!r}. Registered: {sorted(_REGISTRY)}"
        ) from None
    root = Path(base).expanduser() if base else data_dir()
    return root / rel


def require_dataset(name: str, base: str | Path | None = None) -> Path:
    """Like :func:`dataset_path`, but raise ``FileNotFoundError`` if it is missing."""
    path = dataset_path(name, base)
    if not path.exists():
        raise FileNotFoundError(
            f"Dataset {name!r} not found at {path}. "
            f"(data root: {Path(base) if base else data_dir()})"
        )
    return path
