modell: PyStoned
parametrar:
  cet: addi
  fun: prod
  input_cols:
  - CAPEX
  - OPEXp
  kravmetod: absolut
  outlier_filter: true
  output_cols:
  - CU
  rts: crs
  trunkering_max: 0.3
  trunkering_min: 0.162416
timestamp: 2025-07-08_09-28-13
