datum: '2025-08-05'
distribution: halvnormal
effektivitet: "theta_final = exp(-u\u0302)"
ineffDecrease: false
input:
- CU
- MWhl
- MWhh
- MW
- NS
kravmetod: percentilbaserat
modell: SFA Cobb-Douglas kostnadsfront
obs: 136
output: TOTEX
skattning: MLE
trunkering_max: 0.3
trunkering_min: 0.162
