modell: DEA
parametrar:
  input_cols:
  - OPEXp
  - CAPEX_2024_wacc_0p0453_tkr
  outlier_filter: true
  output_cols:
  - CU
  - MW
  - NS
  - MWhl
  - MWhh
  rts: crs
  trunkering_max: 0.3
  trunkering_min: 0.162416
timestamp: 2025-09-17_15-34-29
