modell: DEA
parametrar:
  input_cols:
  - TOTEX_wacc_0p0700
  outlier_filter: true
  output_cols:
  - CU
  - MW
  - NS
  - MWhl
  - MWhh
  rts: crs
  trunkering_max: 0.3
  trunkering_min: 0.162416
timestamp: 2025-08-22_16-47-41
