modell: DEA
parametrar:
  input_cols:
  - CAPEX
  - OPEXp
  outlier_filter: true
  output_cols:
  - CU
  - MW
  - NS
  - MWhl
  - MWhh
  rts: crs
  trunkering_max: 0.3
  trunkering_min: 0.162416
timestamp: 2025-07-07_11-49-42
